version: '3.8'

services:
  midjourney-app:
    build: .
    container_name: midjourney-generator
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      # 从.env文件加载的环境变量
      - MJ_API_SECRET=${MJ_API_SECRET}
      - IMAGINE_URL=${IMAGINE_URL}
      - FETCH_URL_BASE=${FETCH_URL_BASE}
      - ACTION_URL=${ACTION_URL}
      - ACCESS_CODE=${ACCESS_CODE:-your-access-code}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_API_URL=${OPENAI_API_URL:-https://api.openai.com/v1/chat/completions}
    env_file:
      - .env
    volumes:
      - ./images:/app/images:rw # 挂载 images 目录，读写权限
      - /app/node_modules # 防止本地node_modules覆盖容器内的
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M